sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - BUCKET=akerl-go-committed
  - secure: FnrvDrsaacPmgMhm8vpsESNikyaJKEPAMbqSg07ag28wiA2d/nBG4W5Dwbrzv+VGoKgGGTejKvm38xqR61iGqBLjBq9fH8tM68E6pYOLg816ohgr3TE5cV6ZJC3YqvsDqexDSiV21iIEXHF7xHlaMOhQBspcbxJCMyUZNg03COaBbNAr9MJ6ZUNrfHgJbYopkvAYbWJdGPwQTeBQU/30KEFz6OGFvbCtUgvsLyNut1r9W1vam9v6Ffj+4eFW+tvFI2GBTdvGV2M0MshxQ9Yzks7VHGMrZ0eG6CQ5h4EEovVf502HqgKiaZXxztrepnPR6A0MZgbglVPIxvaZKIARcH09i/wip8B0diZIfYr99wpQ+dUwofU+3rksaacPmDxQh6/Dg2WdvGjMb2KFi2e9/N5wjTFmO1TL5ofnv2DqSTAbS+FVJ/rwlqTLrnIbpKx4N2Ck3FdLGopZBXbdBbrPGRkl3VdGcURoq30QEDYpXyoYR8OwwKK1Su+NSEMV4EeDrMs+p9Q83JmLXkDf1S57wPY2AYSlbEeSvWSg7KENii1c+IBvFyGI/KD5bF+LpYg+wx/WCPwINWPuG+7A0z68zKadoeIRFFS6HEAkgPozblVTikfy3NG+ParoqGBLgYCNMT5ES6zIwgSMPoaBvpwfUADrlSckAUIbTQPZcPn2f2Q=
before_install:
- pip install --user awscli
script: make
deploy:
  provider: script
  script: make release && aws s3 cp pkg/payload.zip "s3://$BUCKET/lambdas/payload-$TRAVIS_TAG.zip"
    || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: fGCHwP+QTEEvSUee8EDI37QxLt4Xe4rKgMcsnnrOpoHN3xut88bPeyUK4s73Rt0NJOLoguQXO9fuetpGw3KSk3WfVyY0oe/Obzy0XouobAZa/ALP/QrHt2KxzUkytGja8MwQpAmqjn/gi36UPhAMZOPclAv3XJozDHIBkYfN+y4ze/ZWC90E86UYZSkMgexjEtfeLgxp2SokQoOG4qjZLEuIWqXzvmrSzJ/ohrcmpWlqme5zadFT3Yhnd39+ovD3biTRS2jzefbgXn63gcLCvOsSrknHr5Jz9p2Krw6JrDj4cPG2wtdRZPxDAEVjaXZYajvaB7sM8RwWx030Hx3siFmkum9DfeFBiIfpte2otpUhdksIfrkhzocUdE8F8COcSHRH9OLrQbGdBNY6bd5VRYKomM3j6zIsZt92IJbWbSkZvXeRQo40tY1ovw0KjJ+JhkJffcLZ/03pKyJXkt/LTL6Mtz1wWXf2SMN8QNRJHFLWwgbRohJQoSwdMoSaJAQw+AxP/GJkBoQAfS6eYP8TtSBVc1Jas25+YTODhNv/jQZG72CxyfbC5yDgEfSRDWzrqTGzK5R9oAo07m/Im0ltUL9GcIbEGODVArPoNlt3wyUv0lcimd9uDKa4YPOPzumUxsTQbRdkS0fS/EZKxZbFgwuZ72luNxTW3ePrKi59SEE=
